### ISSUE TITLE
Dual Y inverted way

### ISSUE THREAD

**Issue by UnleashSpirit** [makerbase-mks/MKS-DLC#6]
Hi, I jsut switch from CNC shield to MKS DLC 2.0.
Flash last firmware, MKS_TFT35_CNC_V1.0.2 and last grbl 1.1h
My Y1 and Y2 are turning oposite way
Is there a way to invert only Y2 (without switching cables) ?

**Comment by DirtyEngineer** [comment]
Yes - Use the $3 setting in grbl to invert a specific axis.

**Comment by mks-viva** [comment]
@UnleashSpirit 
Hi! I am sorry, because the hardware has determined that Y1 and Y2 always move in opposite directions.
![image](https://user-images.githubusercontent.com/16629551/102034164-4f817500-3df8-11eb-8b0e-94f8b51f365a.png)
![image](https://user-images.githubusercontent.com/16629551/102034293-966f6a80-3df8-11eb-839a-030c1ce5aeef.png)

**Comment by mks-viva** [comment]
So, you need change the cable.
